Neos:
  Fusion:
    dsl:
      css: PackageFactory\AtomicFusion\StyledComponents\Dsl\CssDslImplementation
  Neos:
    fusion:
      autoInclude:
        PackageFactory.AtomicFusion.StyledComponents: true
